### ISSUE TITLE
graphql-java v15 changed graphql.Assert in ways that breaks graphql-java-spring-webmvc

### ISSUE THREAD

**Issue by skingsland** [graphql-java/graphql-java-spring#31]
I'm trying to run the graphql-java-spring-webmvc web app locally, which works fine with graphql-java `14.1`, but breaks with `15.0`:
```
2020-06-04 21:55:15.014 ERROR 45400 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: graphql.Assert.assertNotNull(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;] with root cause

java.lang.NoSuchMethodError: graphql.Assert.assertNotNull(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
	at graphql.spring.web.servlet.GraphQLInvocationData.<init>(GraphQLInvocationData.java:17) ~[graphql-java-spring-webmvc-1.0.jar!/:na]
	at graphql.spring.web.servlet.components.GraphQLController.graphqlPOST(GraphQLController.java:47) ~[graphql-java-spring-webmvc-1.0.jar!/:na]
	...
```
The problem is that graphql-java version 15 made [changes](https://github.com/graphql-java/graphql-java/commit/2acb557474ca73cec95e07dddf3af54d3ce41722#diff-194b292c3c26a01d4bbfa88fcbd82773) to the `graphql.Assert` class that aren't backwards-compatible. As a result, the call from the GraphQLInvocationData [constructor](https://github.com/graphql-java/graphql-java-spring/blob/master/graphql-java-spring-webmvc/src/main/java/graphql/spring/web/servlet/GraphQLInvocationData.java#L17) to `Assert.assertNotNull()` fails to find a method matching the expected signature.

I don't know if there are other changes in v15 that need to be addressed here as well, but I wanted to bring this one to your attention. I'll stay on v14.1 for now, as a result of this problem.

**Comment by skingsland** [comment]
This is fixed in https://github.com/graphql-java/graphql-java-spring/pull/32, released as version `2.0`, and I've tested it locally and can confirm that it's fixed. (In hindsight, I wish I'd known the fix was only 3 lines of code, cause I could have PR'd that myself, ha ha.) Anyway, thanks for the quick turnaround on this!
